name: analytics_support_example
description: Demonstrates how to use the analytics_support plugin.

publish_to: 'none'

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  analytics_support:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
